name: Pack template
on:
   push:
     branches: [ main ]

jobs:
  github:
    runs-on: ubuntu-latest
    environment: 'github'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Pack
      run: dotnet pack --configuration Release --output nupkgs --version-suffix "nightly-${GITHUB_RUN_ID}" FSharp.Android.Resource.proj
    - name: Push
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/TimLariviere/index.json --name github
        dotnet nuget push "nupkgs/*.nupkg" --source github --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

  nuget:
    runs-on: ubuntu-latest
    environment: 'nuget'
    needs: github
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Pack
      run: dotnet pack --configuration Release --output nupkgs FSharp.Android.Resource.proj
    - name: Push
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
